### PR TITLE
Fix for test config

### PR DESCRIPTION
**Pull request by GbotemiB**
# Closes # (if applicable).

## Changes proposed in this Pull Request
The proposed changes in the test configs intend to fix the infeasibility of the model.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Cool fix @GbotemiB :D
Together with the PR by @finozzifa, this significantly help reproducibility and testing of the workflow!
As CI passes, this PR can be merged

**Comment by hazemakhalek** [comment]
Hey @GbotemiB, did you check the result of the the test config with the current main in last couple of days?

@cpschau caught a small bug that caused the model to be infeasible, and is now corrected in the main branch since Friday afternoon.
Interested to know if this solves the objective value of nan in the test config without the need for load shedding

**Comment by GbotemiB** [comment]
@GbotemiB, I didnt check against the latest changes. I will check and confirm the results.

**Comment by hazemakhalek** [comment]
As communicated with @GbotemiB, the nan issue is only solved with the load shedding for now. An issue is now added to revisit this later. 

I agree with @davide-f, the PR is ready to merge.

**Review by hazemakhalek — APPROVED** [review]
Everything looks good and as agreed

**Pull request merged**
