### PR TITLE
fix MissingOutputException

### PR DESCRIPTION
**Pull request by doneachh**
# Closes # (if applicable).

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by doneachh** [comment]
Hi @davide-f & @energyLS ,
we are running into a MissingOutputException in prepare_gas_network when not using custom_data and !(len(pipelines.loc[pipelines.amount_states_passed >= 2]) > 0) as we dont create the pngs snakemake.output.gas_network_fig_1 and snakemake.output.gas_network_fig_2 there. Implemented a workaround to save empty pngs, when falling in this case. 
Do you have an idea for a better solution or can we merge it like this?

**Review by davide-f — COMMENTED** [review]
Hello @doneachh :D
Great for the interesting comments :)

Personally, I'd go in favor of having some additional plotting rule that could plot desired networks by option, gas being one of them.
I wouldn't be in favor of keeping the plotting within the function itself.

It may be good to discuss it with the others

**Comment by davide-f** [comment]
Can we close this then?

**Comment by doneachh** [comment]
> Can we close this then?

@davide-f Yes, but we should add a new issue for the plotting rule :)

**Comment by davide-f** [comment]
Absolutely agree, feel free to do that:)

**Comment by doneachh** [comment]
@energyLS as discussed in PyPSA-Earth-Sec Meeting --> workaround until plotting is an extra rule

**Comment by energyLS** [comment]
@doneachh it looks like the Missing Output Exception comes from snakemake? Or can you elaborate what the issue here is? If the issue comes from snakemake, then we should just remove the output defined by the snakefile?
Also, can you link here the new issue you have created which refers to a proper plotting rule?

**Comment by davide-f** [comment]
> @energyLS as discussed in PyPSA-Earth-Sec Meeting --> workaround until plotting is an extra rule

Does this mean you agreed to merge?
If so, an issue should be raised to track the #TODO

**Comment by energyLS** [comment]
This all makes sense now, but the CI is failing @doneachh

**Comment by doneachh** [comment]
@energyLS ahh yeah i see, forgot to comment the call of the methods

**Review by energyLS — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
