### PR TITLE
fix type error when converting GADM id

### PR DESCRIPTION
**Pull request by doneachh**
# Closes # (if applicable).

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Review by davide-f — COMMENTED** [review]
Thanks @doneachh :D
As comment, is the other issue linked to this?

I'm unsure whether it is a good idea to address the naming conventions before the merge, though it may be good to discuss with the others.


I create an issue that is linked to these issues you've found

**Comment by doneachh** [comment]
@davide-f Could be probably linked with the other issue (with len(x)) as i used the same config for the run

**Comment by doneachh** [comment]
@davide-f #326 doesnt fix this here. should we leave it like this or fix it as well with the layer id here? Would probably prefer to make it this way as we dont have redundant code then :)

**Comment by davide-f** [comment]
Answered on the other PR, feel free to ping me in discord if I lose it here

**Pull request closed without merging**
