### PR TITLE
Issue 312 use single config

### PR DESCRIPTION
**Pull request by finozzifa**
# Closes # (if applicable).

The code resolves point _Use a single config file_ from Issue #312.

## Changes proposed in this Pull Request

- add [configfile](configfile: "config.pypsa-earth.yaml") in **_Snakefile_**
- replace c_onfig_pypsa_earth_ with s_nakemake.config_

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by finozzifa** [comment]
I have exported the value of the objective function at the end of _solve_network.py_ when I execute

_snakemake --cores all run_test_

The code snippet is

`        with open("./data/objective_function.txt", "w") as obj_func_file:
            obj_func_file.write("Objective function: {} \n".format(n.objective))
            obj_func_file.write("Objective constant: {} \n".format(n.objective_constant))`

**Comment by davide-f** [comment]
This looks awesome to me! :D @finozzifa 
In my opinion we can merge it right away if CI runs.

As a comment, if you use vscode, I recommend to:
1. setup pre-commit:
    conda activate pypsa-earth
    pre-commit install
2. make sure that pypsa-earth is the default python env:
    from vscode:
    view->command pallette->python: select interpreter -> pypsa-earth

**Comment by finozzifa** [comment]
Hi @davide-f ,
thanks. It seems to me that all checks have passed and I already follow your recommendations on the environment and pre-commit. Thanks :)

**Review by davide-f — APPROVED** [review]
As CI passes, I'll be merging this :D
Great @finozzifa :D

**Pull request merged**
