### PR TITLE
Consider "urban_percentage" based on "panning_horizons" wildcard and its effect on all Rules

### PR DESCRIPTION
**Pull request by Eddy-JV**
# Closes # (if applicable).

## Changes proposed in this Pull Request

 @energyLS  **PLEASE review this PR carefully. I added a wildcard for the urban_percentage year in Rule `build_population_layouts`  and therefore added `{planning_horizons}` wildcard to all Rules after that.**

This PR is part of adding Params to all Rules in Snakemake under Issue https://github.com/pypsa-meets-earth/pypsa-earth-sec/issues/330

The following Rules are already done including the work done in this PR:

- [x] add_export.py
- [x] build_base_energy_totals.py
- [x] build_base_industry_totals.py
- [x] build_clustered_population_layouts.py -> _(Had no changes to be done)_
- [x] build_cop_profiles.py
- [x] build_heat_demand.py
- [x] build_industrial_database.py -> _(Had no changes to be done)_
- [x] build_industrial_distribution_key.py
- [x] build_industry_demand.py
- [x] build_population_layouts.py
build_ship_profile.py
build_solar_thermal_profiles.py
build_temperature_profiles.py
copy_config.py
helpers.py
make_summary.py
override_respot.py
plot_network.py
plot_network_eur.py
plot_summary.py
prepare_airports.py
prepare_db.py
prepare_energy_totals.py
prepare_gas_network.py
prepare_heat_data.py
prepare_ports.py
prepare_sector_network.py
prepare_transport_data.py
prepare_transport_data_input.py
prepare_urban_percent.py
solve_network.py

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by energyLS** [comment]
@Eddy-JV thanks for the PR. Only concern is regarding the wildcard; I think for tracability and transparency we should move that to a seperate PR?
Also, I think you have added the wildcard in order to work with myopic foresight? Can you elaborate on this?
At the current stage I am hesitating to merge right away, since the new wildcard is a major change for all users.

**Comment by Eddy-JV** [comment]
> @Eddy-JV thanks for the PR. Only concern is regarding the wildcard; I think for tracability and transparency we should move that to a seperate PR? Also, I think you have added the wildcard in order to work with myopic foresight? Can you elaborate on this? At the current stage I am hesitating to merge right away, since the new wildcard is a major change for all users.

I changed the name of the PR to be only for the urban_perecentage changes. I will do another PR to deal with the Params.

**Comment by Eddy-JV** [comment]
@energyLS  Regarding why I introduced this. In the current workflow, `urban_percentage` for `planning_horitons[0]` is always used. Which is let's say 2030. But if we introduce the wildcard in Rule `build_population_layouts` and some of the following ones whenever necessary, **we will be calculating all these changed rules using the wildcard year and not the first value.**

**Review by energyLS — APPROVED** [review]
Looks great. Currently testing locally as well, if that works out we could merge. @Eddy-JV are there any concerns, or could we merge (given it works locally for me)?

**Comment by energyLS** [comment]
> Looks great. Currently testing locally as well, if that works out we could merge. @Eddy-JV are there any concerns, or could we merge (given it works locally for me)?

@Eddy-JV has agreed bilaterally. Merging now.

**Pull request merged**
