### PR TITLE
Fix emission bug

### PR DESCRIPTION
**Pull request by cpschau**
### Change 1:
When modeling shipping and aviation excluding international bunker fuels, it was discovered that the corresponding emission columns in the loads dataframe contained NaN values. This issue arose from passing a pandas Series instead of a scalar when adding the load component, specifically in lines 1078 and 1408 of `prepare_sector_network.py`.

### Change 2:
The multiplication of the p_set-value for residential and services gas emissions with the scalar 8760 had to be removed, as the value must correspond to the hourly emission load, as is set for every hour of the dynamic dataframe.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Review by hazemakhalek — APPROVED** [review]
Everything seems alright and as discussed

**Comment by davide-f** [comment]
> Everything seems alright and as discussed
> 

Sorry to jump in but are you sure to drop the 8760 after .mean()?
If I get right the .mean() ensures to get an average value and with 8760 we turn the value to be an annual quantity.
Or do I get it wrong?

**Comment by hazemakhalek** [comment]
Yes we tested it today, this was actually the reason for the infeasibility :)

**Comment by hazemakhalek** [comment]
@davide-f To give you more details

The value is set for every time step, so before this change, the total emissions from the residential and services sectors were orders of magnitude higher than what they should be. 

Below you can see the yearly emission values in Mtons! before this update. The entire limit of Brazil is 300-400 Mtons 😄 
image

**Comment by davide-f** [comment]
Loool, nice catch!

**Pull request merged**
